version: "3.6"
services:
  user-api:
    build:
      context: ./
    depends_on:
      - rabbitmq
    ports:
      - "8085:80"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
networks: 
  default: 
    external: 
      name: external-network
